def polish_object(object_name):
    polish_objects = {
        "person": "osoba",
        "bicycle": "rower",
        "car": "samochód",
        "motorcycle": "motocykl",
        "airplane": "samolot",
        "bus": "autobus",
        "train": "pociąg",
        "truck": "ciężarówka",
        "boat": "łódź",
        "traffic light": "sygnalizacja świetlna",
        "fire hydrant": "hydrant przeciwpożarowy",
        "stop sign": "znak stop",
        "parking meter": "parkometr",
        "bench": "ławka",
        "bird": "ptak",
        "cat": "kot",
        "dog": "pies",
        "horse": "koń",
        "sheep": "owca",
        "cow": "krowa",
        "elephant": "słon",
        "bear": "niedźwiedź",
        "giraffe": "żyrafa",
        "backpack": "plecak",
        "umbrella": "parasolka",
        "handbag": "torebka",
        "tie": "krawat",
        "suitcase": "walizka",
        "skis": "narty",
        "sports ball": "piłka",
        "kite": "latawiec",
        "baseball bat": "kij baseballowy",
        "baseball glove": "rekawica baseballowa",
        "skateboard": "deskorolka",
        "surfboard": "deska surfingowa",
        "tennis racket": "rakieta tenisowa",
        "bottle": "butelka",
        "wine glass": "Kieliszek do wina",
        "cup": "kubek",
        "fork": "widelec",
        "knife": "nóż",
        "spoon": "łyzka",
        "bowl": "miska",
        "banana": "banan",
        "apple": "jabłko",
        "sandwich": "kanapka",
        "orange": "pomarańcza",
        "broccoli": "brokuł",
        "carrot": "marchewka",
        "donut": "pączek",
        "cake": "ciasto",
        "chair": "krzesło",
        "couch": "kanapa",
        "potted plant": "roślina",
        "bed": "łóżko",
        "toilet": "toaleta",
        "tv": "telewizor",
        "mouse": "myszka",
        "remote": "pilot",
        "keyboard": "klawiatura",
        "cell phone": "telefon",
        "microwave": "mikrofala",
        "oven": "piec",
        "toaster": "toster",
        "sink": "zlew",
        "refrigerator": "lodówka",
        "book": "ksiażka",
        "clock": "zegar",
        "vase": "wazon",
        "scissors": "nożyczki",
        "teddy bear": "pluszak",
        "hair drier": "szuszarka do włosow",
        "toothbrush": "szczoteczka",
        "dining table": "stoł"

    }
    if object_name in polish_objects:
        return polish_objects[object_name]
    else:
        return object_name